name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Continue
        run: cat test.txt
