name: Deploy apps

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      pr_opened:
        type: boolean
        required: true
        default: false
  push:
    branches:
      - "feat/*"
      - "feature/*"

permissions:
  id-token: write # Required for requesting the JWT through OIDC
  contents: read

jobs:
  deploy_apps:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Branch
        if: ${{ inputs.pr_opened }}
        run: |
          echo "Deploy apps workflow "
          echo "Input branch: ${{ inputs.branch_name }}"
          echo "Current branch"
