name: Deploy infra

on:
  workflow_dispatch:
jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Continue
        run: echo "Deploy infra workflow"
