name: Destroy infra

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
jobs:
  destroy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Deploy infra
        run: echo "Deploy infra workflow"

      - name: Trigger app deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "deploy-apps.yml"
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
