name: Entrypoint workflow

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main
jobs:
  entrypoint:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR branch name contains 'feat' or 'feature'
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ "$BRANCH_NAME" =~ feat|feature ]]; then
            echo "Branch name is valid: $BRANCH_NAME"
          else
            echo "Branch name does not match criteria. Exiting."
            exit 1
          fi
      - name: wasup
        run: echo "wasup"

      - name: Trigger Infra Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "deploy-infra.yml"
          ref: main
          token: ${{ secrets.PAT }}
          inputs: '{"branch": "${{ github.head_ref }}"}'
