# .github/workflows/workflow-1.yml
name: PR Created - Check Feature Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main # Or whatever the target branch is

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name contains "feat" or "feature"
        run: |
          branch_name="${{ github.head_ref }}"
          if [[ ! "$branch_name" =~ ^(feat|feature) ]]; then
            echo "Branch name doesn't contain 'feat' or 'feature', skipping workflow.";
            exit 0;
          fi

      - name: checkout
        uses: actions/checkout@v4

      - name: Trigger Workflow 2 with branch name as input
        uses: dzanan-cukurija/test-flow/.github/workflows/deploy-infra.yml@main # Call the workflow directly here
        with:
          branch_name: ${{ github.head_ref }} # Pass feature branch name as input
